name: update-translations

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      SPHINXINTL_TRANSIFEX_ORGANIZATION_NAME: tkoyama010
      SPHINXINTL_TRANSIFEX_PROJECT_NAME: pymapdl-doc
      TX_TOKEN: ${{ secrets.TX_TOKEN }}

    steps:
    - uses: actions/checkout@v4
    - name: Get date
      id: get-date
      run: |
        echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        echo "yyyymm=$(/bin/date -u "+%Y%m")" >> $GITHUB_OUTPUT
      shell: bash
    - name: cache pip
      id: cache-pip
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.local/
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ steps.get-date.outputs.yyyymm }}
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10
    - name: Get Job URL
      uses: Tiryoh/gha-jobid-action@v1
      id: jobs
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        job_name: script
    - name: checkout with submodule
      uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.PERSONAL_ACCESSTOKEN }}
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v3
      with:
        host: github.com
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Install dependencies
      run: |
        (cd pymapdl; git fetch origin; git checkout main; git reset --hard origin/main; git branch -a)
        pip install -U pip setuptools
        pip install -r ./requirements.txt
    - name: Install Transifex CLI
      run: |
        curl -o- https://raw.githubusercontent.com/transifex/cli/main/install.sh | bash
        mv tx /usr/local/bin/tx
        tx --version
    - name: Update translations
      run: sh ./locale/update.sh
    - name: After success
      run: |
        git branch -a
        git checkout main  # attach this repo
        git config --global user.email "pymapdl-auto-update"
        git config --global user.name "pymapdl-auto-update"
        git add locale
        git add pymapdl
        git commit -m "[skip ci] by GHA https://github.com/${{ github.repository }}/actions/runs/${{ github.run_number }}"
    - name: GitHub Push
      if: github.event_name != 'pull_request'
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
